USE master
GO
DROP DATABASE UTRANSPORTDATABASE
GO
CREATE DATABASE UTRANSPORTDATABASE
GO
USE UTRANSPORTDATABASE
GO

CREATE TABLE TRAILER_STATUS
(
	 TRAILER_STATUS_ID INT PRIMARY KEY IDENTITY(1,1),
	 TRAILER_STATUS_NAME VARCHAR(20)
)

INSERT INTO TRAILER_STATUS VALUES('Active')
INSERT INTO TRAILER_STATUS VALUES('InActive')

CREATE TABLE TRAILER
(
	TRAILER_ID INT PRIMARY KEY IDENTITY(1,1),
	TRAILER_REGISTRATIONNUMBER VARCHAR(17),
	TRAILER_BRAND VARCHAR(20),
	TRAILER_NAME VARCHAR(20),
	TRAILER_IMAGE_NAME VARCHAR(20),
	TRAILER_IMAGE IMAGE NULL,
	TRAILER_STATUS_ID INT,
	TRAILER_WEIGHT INT NULL
	FOREIGN KEY (TRAILER_STATUS_ID) REFERENCES TRAILER_STATUS (TRAILER_STATUS_ID)
)
INSERT INTO TRAILER VALUES('FWEF','FWEF','FWEFW','','',1,200)

CREATE TABLE VEHICLE_STATUS
(
	VEHICLE_STATUS_ID INT PRIMARY KEY IDENTITY(1,1),
	VEHICLE_STATUS_NAME VARCHAR(20)
)

INSERT INTO VEHICLE_STATUS VALUES('Active')
INSERT INTO VEHICLE_STATUS VALUES('InActive')


CREATE TABLE VEHICLE
(
	VEHICLE_ID INT PRIMARY KEY IDENTITY(1,1),
	VEHICLE_REGISTRATIONNUMBER VARCHAR(17),
	VEHICLE_PLATENUMBER VARCHAR(8),
	VEHICLE_BRAND VARCHAR(20),
	VEHICLE_NAME VARCHAR(20),
	VEHICLE_IMAGE_NAME VARCHAR(20),
	VEHICLE_IMAGE IMAGE NULL,
	VEHICLE_STATUS_ID INT,
	VEHICLE_WEIGHT INT NULL, 
	TRAILER_ID INT NULL,
	VEHICLE_LICENCE_DISC_EXPIARY DATE,
	VEHICLE_LICENCE_DISC_NO VARCHAR(12),
	FOREIGN KEY (TRAILER_ID) REFERENCES TRAILER (TRAILER_ID) ON DELETE  SET NULL,
	FOREIGN KEY (VEHICLE_STATUS_ID) REFERENCES VEHICLE_STATUS (VEHICLE_STATUS_ID)
)

INSERT INTO VEHICLE VALUES('561516','5FWE','F4W4','WEDWE','','',1,200,1,'2019-6-6','BNVB')


CREATE TABLE CHECK_STATUS
(
	CHECK_STATUS_ID INT PRIMARY KEY IDENTITY(1,1),
	CHECK_STATUS_NAME VARCHAR(10)
)
CREATE TABLE BEFORE_START
(
	BEFORE_START_ID INT PRIMARY KEY IDENTITY(1,1),
	BEFORE_START_NAME VARCHAR(20),
	BEFORE_START_DESCRIPTION VARCHAR(50) NULL
)

CREATE TABLE AFTER_START
(
	AFTER_START_ID INT PRIMARY KEY IDENTITY(1,1),
	AFTER_START_NAME VARCHAR(20),
	AFTER_START_DESCRIPTION VARCHAR(50) NULL
)


CREATE TABLE ANCILLARY_EQUIPMENT
(
	ANCILLARY_EQUIPMENT_ID INT PRIMARY KEY IDENTITY(1,1),
	ANCILLARY_EQUIPMENT_NAME VARCHAR(20),
	ANCILLARY_EQUIPMENT_DESCRIPTION VARCHAR(50) NULL
)


CREATE TABLE BEFORE_CHECK
(
	BEFORE_CHECK_ID INT PRIMARY KEY IDENTITY(1,1),	
	CHECK_STATUS_ID INT ,
	BEFORE_CHECK_TIME DATETIME,	
	BEFORE_START_ID INT 
	FOREIGN KEY (CHECK_STATUS_ID) REFERENCES CHECK_STATUS (CHECK_STATUS_ID),
	FOREIGN KEY (BEFORE_START_ID) REFERENCES BEFORE_START (BEFORE_START_ID)
)

CREATE TABLE AFTER_CHECK
(
	AFTER_CHECK_ID INT PRIMARY KEY IDENTITY(1,1),
	CHECK_STATUS_ID INT,
	AFTER_CHECK_TIME DATETIME,
	AFTER_START_ID INT,
	VEHICLE_CHECK_ID INT
	FOREIGN KEY (CHECK_STATUS_ID) REFERENCES CHECK_STATUS (CHECK_STATUS_ID),
	FOREIGN KEY (AFTER_START_ID) REFERENCES AFTER_START (AFTER_START_ID)
)


CREATE TABLE EQUIPMENT_CHECK
(
	EQUIPMENT_CHECK_ID INT PRIMARY KEY IDENTITY(1,1),
	CHECK_STATUS_ID INT,
	EQUIPMENT_CHECK_TIME DATETIME,
	ANCILLARY_EQUIPMENT_ID INT,
	VEHICLE_CHECK_ID INT,
	FOREIGN KEY (CHECK_STATUS_ID) REFERENCES CHECK_STATUS (CHECK_STATUS_ID),
	FOREIGN KEY (ANCILLARY_EQUIPMENT_ID) REFERENCES ANCILLARY_EQUIPMENT (ANCILLARY_EQUIPMENT_ID)
)

CREATE TABLE VEHICLE_CHECK
(
	VEHICLE_CHECK_ID INT PRIMARY KEY IDENTITY(1,1),
	VEHICLE_CHECK_STATUS VARCHAR(10),
	BEFORE_CHECK_ID INT,
	AFTER_CHECK_ID INT,
	EQUIPMENT_CHECK_ID INT,
	VEHICLE_ID INT,	
	FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (VEHICLE_ID) ON DELETE SET NULL,	
	FOREIGN KEY (BEFORE_CHECK_ID) REFERENCES BEFORE_CHECK (BEFORE_CHECK_ID),
	FOREIGN KEY (AFTER_CHECK_ID) REFERENCES AFTER_CHECK(AFTER_CHECK_ID),
	FOREIGN KEY (EQUIPMENT_CHECK_ID) REFERENCES EQUIPMENT_CHECK(EQUIPMENT_CHECK_ID)
)



CREATE TABLE TRAILER_CHECK
(
	TRAILER_CHECK_ID INT PRIMARY KEY IDENTITY(1,1),
	CHECK_STATUS VARCHAR(10),
	TRAILER_CHECK_TIME DATETIME,
	TRAILER_ID INT,
	FOREIGN KEY (TRAILER_ID) REFERENCES TRAILER(TRAILER_ID) ON DELETE SET NULL
)

CREATE TABLE TRAILER_COMPONENT
(
	TRAILER_COMPONENT_ID INT PRIMARY KEY IDENTITY(1,1),
	TRAILER_COMPONENT_NAME VARCHAR(20),
	TRAILER_COMPONENT_DESCRIPTION VARCHAR(50) NULL
)

CREATE TABLE DEALERSHIP
(
	DEALERSHIP_ID INT PRIMARY KEY IDENTITY(1,1),
	DEALERSHIP_NAME VARCHAR(20),
	DEALERSHIP_REGISTRATION_NUMBER VARCHAR(10),
	DEALERSHIP_CONTACT_NUMBER VARCHAR (9),
	DEALERSHIP_LOCATION VARCHAR(50)
)

CREATE TABLE VEHICLE_DEALERSHIP_SERVICE
(
	VEHICLE_SERVICE_ID INT PRIMARY KEY IDENTITY(1,1),
	VEHICLE_SERVICE_DATE DATE,
	VEHICLE_SERVICE_NEXT_DATE DATE,
	VEHICLE_ID INT,
	DEALERSHIP_ID INT,
	FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (VEHICLE_ID) ON DELETE CASCADE,
	FOREIGN KEY (DEALERSHIP_ID) REFERENCES DEALERSHIP (DEALERSHIP_ID) ON DELETE SET NULL
)



CREATE TABLE TITLE
(
	TITLE_ID INT PRIMARY KEY IDENTITY(1,1),
	TITLE_NAME VARCHAR(10)
)

INSERT INTO TITLE VALUES('Mr')
INSERT INTO TITLE VALUES('Miss')
INSERT INTO TITLE VALUES('Mrs')
INSERT INTO TITLE VALUES('Dr')
INSERT INTO TITLE VALUES('Prof')
INSERT INTO TITLE VALUES('Mister')

CREATE TABLE EMPLOYEE_CONTRACT
(
	EMPLOYEE_CONTRACT_ID VARCHAR(25) PRIMARY KEY,
	EMPLOYEE_CONTRACT_SALARY INT,
	EMPLOYEE_CONTRACT_START_DATE DATE,
	EMPLOYEE_CONTRACT_END_DATE DATE,
)
INSERT INTO EMPLOYEE_CONTRACT VALUES ('1',56,'','')

CREATE TABLE EMPLOYEE_TYPE
(
	EMPLOYEE_TYPE_ID INT PRIMARY KEY IDENTITY(1,1),
	EMPLOYEE_TYPE_NAME VARCHAR(15),
	EMPLOYEE_TYPE_DESCRIPTION VARCHAR(50)
)

INSERT INTO EMPLOYEE_TYPE VALUES('Administrator','Administartes')
INSERT INTO EMPLOYEE_TYPE VALUES('Supervisor','Overlooks all operations')
INSERT INTO EMPLOYEE_TYPE VALUES('Manager',' manages the company')
INSERT INTO EMPLOYEE_TYPE VALUES('Driver','drives the vehicle')

CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID INT PRIMARY KEY IDENTITY(1,1),
	TITLE_ID INT,
	EMPLOYEE_IMAGE IMAGE,
	EMPLOYEE_IMAGE_NAME VARCHAR(20),
	EMPLOYEE_NAMES VARCHAR(50),
	EMPLOYEE_SURNAME VARCHAR(20),
	EMPLOYEE_EMAIL_ADDRESS VARCHAR(50),
	EMPLOYEE_CONTACT_NO VARCHAR(9),
	EMPLOYEE_IDENTITY_NO VARCHAR(13),
	EMPLOEE_DATEOFBIRTH DATE,
	EMPLOYEE_GENDER VARCHAR (8),
	EMPLOYEE_CONTRACT_ID VARCHAR (25) NULL,
	EMPLOYEE_TYPE_ID INT,
	EMPLOYEE_CONTACT_NO_CODE VARCHAR(6),
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE (TITLE_ID) ,
	FOREIGN KEY (EMPLOYEE_CONTRACT_ID) REFERENCES EMPLOYEE_CONTRACT (EMPLOYEE_CONTRACT_ID),
	FOREIGN KEY (EMPLOYEE_TYPE_ID) REFERENCES EMPLOYEE_TYPE (EMPLOYEE_TYPE_ID) ON DELETE SET NULL
)

INSERT INTO EMPLOYEE VALUES(1,'','','Jake','Perolta','jake@p.com','734529573','9805125478016','06-Sep-1992','Female','1',2,'')
INSERT INTO EMPLOYEE VALUES(5,'','','Sandy','Mabaso','sandy@gmail.com','786137945','9812485658516','16-may-1990','Female','1',4,'')
INSERT INTO EMPLOYEE VALUES(4,'','','Mike','Chauke','Mike@tuks.co.za','734529573','90061258016','06-may-1971','Male','1',3,'')
INSERT INTO EMPLOYEE VALUES(3,'','','Themba','Mathe','ThembaMathe@yahoo.com','632791058','9906155478016','01-jan-1999','Male','1',1,'')


CREATE TABLE USERS
(
	USERS_ID INT PRIMARY KEY IDENTITY (1,1),
	EMPLOYEE_ID INT,
	USERS_USERNAME VARCHAR(50),
	USERS_PASSWORD VARCHAR(100),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE
)
INSERT INTO USERS VALUES(1,'jake@p.com','12345')
INSERT INTO USERS VALUES(1,'ThembaMathe@yahoo.com','qwert')

CREATE TABLE SYSTEM_ACCRESS
(
	SYSTEM_ACCRESS_ID INT PRIMARY KEY IDENTITY(1,1),
	SYSTEM_ACCRESS_DATA VARCHAR(10),
	SYSTEM_ACCRESS_AUDITTRAIL VARCHAR(10),
	SYSTEM_ACCRESS_CLIENT VARCHAR(10),
	SYSTEM_ACCRESS_EMPLOYEE VARCHAR(10),
	SYSTEM_ACCRESS_MAINTAIN VARCHAR(10),
	SYSTEM_ACCRESS_PRODUCT VARCHAR(10),
	SYSTEM_ACCRESS_SUPPLIER VARCHAR(10),
	SYSTEM_ACCRESS_USERS VARCHAR(10),
	SYSTEM_ACCRESS_VEHICLE VARCHAR(10),
	SYSTEM_ACCRESS_REPORTING VARCHAR(10),
	USERS_ID INT,	
	FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID) ON DELETE CASCADE
)

CREATE TABLE OTP
(
	OTP_ID INT PRIMARY KEY IDENTITY(1,1),
	OTP_CODE INT,
	OTP_DATE DATETIME,
	USERS_ID INT,	
	FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID) ON DELETE CASCADE
)


INSERT INTO OTP VALUES(125,'2019-09-28 12:43:00.000',1)
INSERT INTO OTP VALUES(125,'2019-09-28 12:44:00.000',1)
INSERT INTO OTP VALUES(125,'2019-09-28 12:45:00.000',1)
INSERT INTO OTP VALUES(125,'2019-09-28 12:46:00.000',1)

CREATE TABLE AUDIT_TRAIL_TYPE
(
	AUDIT_TRAIL_TYPE_ID INT PRIMARY KEY IDENTITY(1,1),
	AUDIT_TRAIL_TYPE_NAME VARCHAR(20),
)

INSERT INTO AUDIT_TRAIL_TYPE VALUES('Create')
INSERT INTO AUDIT_TRAIL_TYPE VALUES('Read')
INSERT INTO AUDIT_TRAIL_TYPE VALUES('Update')
INSERT INTO AUDIT_TRAIL_TYPE VALUES('Delete')

CREATE TABLE AUDIT_TRAIL
(
	AUDIT_TRAIL_ID INT PRIMARY KEY IDENTITY(1,1),
	EMPLOYEE_ID INT,
	AUDIT_TRAIL_DATE DATETIME,
	AUDIT_TRAIL_TYPE_ID INT,
	AUDIT_TRAIL_DESCRIPTION VARCHAR(50),
	AUDIT_TRAIL_DEVICE VARCHAR(100),
	FOREIGN KEY (AUDIT_TRAIL_TYPE_ID) REFERENCES AUDIT_TRAIL_TYPE(AUDIT_TRAIL_TYPE_ID) ON DELETE SET NULL ,
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE SET NULL  
)

CREATE TABLE MAINTENANCE_STATUS
(
	MAINTENANCE_STATUS_ID INT PRIMARY KEY IDENTITY(1,1),
	MAINTENANCE_STATUS_NAME VARCHAR(12)
)

INSERT INTO MAINTENANCE_STATUS VALUES('Not Started')
INSERT INTO MAINTENANCE_STATUS VALUES('In Progress')
INSERT INTO MAINTENANCE_STATUS VALUES('Complete')

CREATE TABLE MAINTENANCE
(
	MAINTENANCE_ID INT PRIMARY KEY IDENTITY(1,1),
	MAINTENANCE_REF VARCHAR(20),
	VEHICLE_ID INT, 
	EMPLOYEE_ID INT,
	MAINTENANCE_STATUS_ID INT,
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ON DELETE SET NULL,
	FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID) ON DELETE SET NULL,
	FOREIGN KEY (MAINTENANCE_STATUS_ID) REFERENCES MAINTENANCE_STATUS(MAINTENANCE_STATUS_ID) ON DELETE SET NULL
)

INSERT INTO MAINTENANCE VALUES('516516131',1,1,3)
INSERT INTO MAINTENANCE VALUES('516163153',1,3,1)


CREATE TABLE TRUCK_PICKUP_STATUS
(
	TRUCK_PICKUP_STATUS_ID INT PRIMARY KEY IDENTITY(1,1),
	TRUCK_PICKUP_STATUS_NAME VARCHAR(30)
)
INSERT INTO TRUCK_PICKUP_STATUS VALUES('Picked Up')
INSERT INTO TRUCK_PICKUP_STATUS VALUES('Did not Picked Up')


CREATE TABLE PRODUCT_TYPE
(
	PRODUCT_TYPE_ID INT PRIMARY KEY IDENTITY(1,1),
	PRODUCT_TYPE_NAME VARCHAR(20),	
	PRODUCT_TYPE_DESCRIPTION VARCHAR (100)
)
INSERT INTO PRODUCT_TYPE VALUES('Wheel','Found at the bottom of the vehicle and spins')
CREATE TABLE PRODUCT
(
	PRODUCT_ID INT PRIMARY KEY IDENTITY(1,1),
	PRODUCT_NAME VARCHAR(20),
	PRODUCT_QUANTITY INT,
	PRODUCT_TYPE_ID INT,
	PRODUCT_DESCRIPTION VARCHAR (100),
	FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE (PRODUCT_TYPE_ID) ON DELETE SET NULL
)

INSERT INTO PRODUCT VALUES('FireStone Tires',10,1,'Built for heavy duty trucks')
INSERT INTO PRODUCT VALUES('MileStone',20,1,'Built for light duty trucks')

CREATE TABLE  MAINTENANCE_PRODUCT
(
	MAINTENANCE_PRODUCT INT PRIMARY KEY IDENTITY(1,1),
	MAINTENANCE_ID INT,
	PRODUCT_ID INT,
	MAINTENANCE_PRODUCT_QUANTITY INT,		
	FOREIGN KEY (MAINTENANCE_ID) REFERENCES MAINTENANCE (MAINTENANCE_ID) ON DELETE CASCADE,		
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE SET NULL
)

INSERT INTO MAINTENANCE_PRODUCT VALUES(1,1,5)
INSERT INTO MAINTENANCE_PRODUCT VALUES(1,2,3)
INSERT INTO MAINTENANCE_PRODUCT VALUES(1,1,3)

CREATE TABLE SERVICE_ITEM
(
	DEALERSHIP_ID INT,
	PRODUCT_ID INT,
	PRODUCT_NAME VARCHAR(20),
	SERVICE_ITEM_QUANTITY INT,
	FOREIGN KEY (DEALERSHIP_ID) REFERENCES DEALERSHIP (DEALERSHIP_ID) ON DELETE SET NULL,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE SET NULL
)

CREATE TABLE ORDERS_STATUS
(
	ORDERS_STATUS_ID INT PRIMARY KEY IDENTITY(1,1),
	ORDERS_STATUS_NAME VARCHAR(20)
)

INSERT INTO ORDERS_STATUS VALUES('Placed')
INSERT INTO ORDERS_STATUS VALUES('Recieved')
INSERT INTO ORDERS_STATUS VALUES('Payed')

CREATE TABLE SUPPLIER
(
	SUPPLIER_ID INT PRIMARY KEY IDENTITY(1,1),
	SUPPLIER_NAME VARCHAR(30),
	SUPPLIER_REGISTRATION_NUMBER VARCHAR(20),
	SUPPLIER_EMAIL VARCHAR(50),
	SUPPLIER_CONTACT_NUMBER_CODE VARCHAR(7),
	SUPPLIER_CONTACT_NO VARCHAR (10),
	SUPPLIER_ADDRESS_BOX VARCHAR (15),
	SUPPLIER_ADDRESS_STREET VARCHAR(50),
	SUPPLIER_ADDRESS_TOWN VARCHAR (20),
	SUPPLIER_ADDRESS_CODE VARCHAR (4),
	SUPPLIER_BANK_DETAILS VARCHAR(50)
)

CREATE TABLE ORDERS
(
	ORDERS_ID VARCHAR(20) PRIMARY KEY ,
	ORDERS_STATUS_ID INT,
	SUPPLIER_ID INT,
	FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID) ON DELETE SET NULL,
	FOREIGN KEY (ORDERS_STATUS_ID) REFERENCES ORDERS_STATUS(ORDERS_STATUS_ID)
)

CREATE TABLE ORDERS_LINE
(
	ORDERS_LINE_ID INT PRIMARY KEY IDENTITY(1,1),
	ORDERS_LINE_QUANTITY INT,
	ORDERS_ID VARCHAR(20),
	PRODUCT_ID INT,
	FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS(ORDERS_ID) ON DELETE CASCADE,	
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE SET NULL
)

CREATE TABLE TRIP
(
	TRIP_ID INT  PRIMARY KEY IDENTITY(1,1),
	TRIP_NUMBER_OF_TONS_LOADED	INT,
	TRIP_NUMBER_OF_TONS_OFFLOADED INT,
	MINE_NAME INT,
	DESTINATION VARCHAR(50),
	DELEIVERY_DATE VARCHAR (50),
	TIME_OF_DEPARTURE DATETIME,
	LOCATIONS_ID INT,
	LOCATIONS_NAME VARCHAR (50)

)

CREATE TABLE DELIVERY_LIST
(
	DELIVERY_LIST_ID INT PRIMARY KEY IDENTITY(1,1),
	MINE_NAME VARCHAR(20),
	DESTINATION VARCHAR(20),
	CLIENT_CONTACT_NUMBER INT,
	TONS DECIMAL,
	DELIVERY_LIST_DATE DATETIME,
	EMPLOYEE_VEHICLE_TRUCK_PICKUP_ID INT
)


CREATE TABLE WEIGH_BILL_TYPE
(
	WEIGH_BILL_TYPE_ID INT PRIMARY KEY IDENTITY(1,1),
	WEIGH_BILL_TYPE_NAME VARCHAR (20),	
)
CREATE TABLE WEIGH_BILL
(
	WEIGH_BILL_ID INT PRIMARY KEY IDENTITY(1,1),
	WEIGH_BILL_REFERENCE_NUMBER VARCHAR(20),
	TRIP_ID INT,
	TRIP_DESCRIPTION VARCHAR (40),
	WEIGH_BILL_NUMBER_OF_TONS_LOADED DECIMAL,
	WEIGH_BILL_NUMBER_OF_TONS_OFFLOADED DECIMAL,
	WEIGH_BILL_MINE_NAME VARCHAR(20),
	WEIGH_BILL_DESTINATION VARCHAR(20),
	WEIGH_BILL_TYPE_ID  INT
	FOREIGN KEY (TRIP_ID ) REFERENCES TRIP(TRIP_ID ) ON DELETE CASCADE,	
	FOREIGN KEY (WEIGH_BILL_TYPE_ID ) REFERENCES WEIGH_BILL_TYPE(WEIGH_BILL_TYPE_ID ) ON DELETE CASCADE
)

CREATE TABLE CLIENT
(
	CLIENT_ID INT PRIMARY KEY IDENTITY(1,1),
	CLIENT_NAME VARCHAR(50),
	CLIENT_EMAIL_ADDRESS VARCHAR(50),
	CLIENT_ADDRESS_BOX VARCHAR (15),
	CLIENT_ADDRESS_STREET VARCHAR(30),
	CLIENT_ADDRESS_TOWN VARCHAR (20),
	CLIENT_ADDRESS_CODE VARCHAR (4),
	CLIENT_CONTACT_NUMBER_CODE VARCHAR(6),
	CLIENT_CONTACT_NUMBER INT
)
CREATE TABLE PROVINCE
(
	PROVINCE_ID INT PRIMARY KEY IDENTITY(1,1),
	PROVINCE_NAME VARCHAR (20)
)

INSERT INTO PROVINCE VALUES ('Limpopo')
INSERT INTO PROVINCE VALUES ('Gauteng')
INSERT INTO PROVINCE VALUES ('Mpumalanga')
INSERT INTO PROVINCE VALUES ('North-West')
INSERT INTO PROVINCE VALUES ('Free State')
INSERT INTO PROVINCE VALUES ('Eastern Cape')
INSERT INTO PROVINCE VALUES ('Western Cape')
INSERT INTO PROVINCE VALUES ('Kwa-Zulu-Natal')
INSERT INTO PROVINCE VALUES ('Northern Cape')

CREATE TABLE MINE
(
	MINE_ID INT PRIMARY KEY IDENTITY(1,1),
	MINE_NAME VARCHAR(20),
	PROVINCE_ID INT,
	FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCE(PROVINCE_ID)
)


CREATE TABLE  TRUCK_POINT
(
	TRUCK_POINT_ID INT PRIMARY KEY IDENTITY (1,1),
	TRUCK_STOP_DESTINATION VARCHAR (200)
)

CREATE TABLE LOCATIONS
(
	 LOCATIONS_ID INT PRIMARY KEY IDENTITY(1,1),
	  LOCATIONS_NAME VARCHAR(20)
)


CREATE TABLE DESTINATION
(
	DESTINATION_ID INT PRIMARY KEY IDENTITY(1,1),
	DESTINATION_NAME VARCHAR (50)
)


CREATE TABLE CLIENT_MINE
(	
	CLIENT_MINE_ID INT IDENTITY(1,1) PRIMARY KEY,
	MINE_ID INT,
	CLIENT_ID INT,
	DESTINATION_ID INT 	
	FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) ON DELETE CASCADE,
	FOREIGN KEY (MINE_ID) REFERENCES MINE(MINE_ID) ON DELETE CASCADE,
	FOREIGN KEY (DESTINATION_ID) REFERENCES DESTINATION(DESTINATION_ID) ON DELETE CASCADE
)

CREATE TABLE APIKEY
(
	APIKEY_ID INT PRIMARY KEY IDENTITY(1,1),
	APIKEY_KEY VARCHAR(100)
)

INSERT INTO APIKEY VALUES('AIzaSyAFL9k8BebjW9m_luJSzVImRP5-zhgm3Rk')

CREATE TABLE CLIENT_ROUTE
(
	CLIENT_ROUTE_ID INT PRIMARY KEY IDENTITY(1,1),
	CLIENT_MINE_ID INT,
	CLIENT_ROUTE_KEY_LOCATIONS1 VARCHAR(100),
	CLIENT_ROUTE_KEY_LOCATIONS2 VARCHAR(100),
	CLIENT_ROUTE_KEY_LOCATIONS3 VARCHAR(100),
	FOREIGN KEY (CLIENT_MINE_ID) REFERENCES CLIENT_MINE(CLIENT_MINE_ID) ON DELETE CASCADE
)

CREATE TABLE ROUTE_POINT
(
	ROUTE_POINT_ID INT PRIMARY KEY IDENTITY(1,1),
	LOCATIONS_ID INT,
	CLIENT_ROUTE_ID INT,
	DESCRIPTIONS VARCHAR (200),	
	FOREIGN KEY (LOCATIONS_ID) REFERENCES LOCATIONS(LOCATIONS_ID) ON DELETE CASCADE,
	FOREIGN KEY (CLIENT_ROUTE_ID) REFERENCES CLIENT_ROUTE(CLIENT_ROUTE_ID) ON DELETE CASCADE
)

CREATE TABLE DISCUSSIONS
(
	DISCUSSIONS_ID INT PRIMARY KEY IDENTITY(1,1),
	DISCUSSIONS_MESSAGE VARCHAR(160),	
	EMPLOYEE_ID INT,
	EMPLOYEE_TYPE_ID INT,
	DISCUSSIONS_DATE DATETIME,
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ON DELETE SET NULL,
	FOREIGN KEY (EMPLOYEE_TYPE_ID) REFERENCES EMPLOYEE_TYPE (EMPLOYEE_TYPE_ID) ON DELETE SET NULL
)


CREATE TABLE TRUCK_ALLOCATION
(
	TRUCK_ALLOCATION_ID INT PRIMARY KEY IDENTITY(1,1),
	VEHICLE_ID INT,
	EMPLOYEE_ID INT,	
	CLIENT_ID INT,
	EMPLOYEE_DRIVER_ID INT,
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ON DELETE SET NULL,
	FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (VEHICLE_ID) ON DELETE CASCADE,
	FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) ON DELETE CASCADE
)

CREATE TABLE TRUCK_PICKUP_LOG
(
	TRUCK_PICKUP_LOG_ID INT PRIMARY KEY IDENTITY(1,1),	
	TRUCK_ALLOCATION_ID INT,
	TRUCK_PICKUP_LOG_DATE DATETIME,	
	EMPLOYEE_ID INT,
	FOREIGN KEY (TRUCK_ALLOCATION_ID) REFERENCES TRUCK_ALLOCATION(TRUCK_ALLOCATION_ID) ON DELETE SET NULL,	
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ON DELETE SET NULL,
)

