//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_TRAIL
    {
        public int AUDIT_TRAIL_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<System.DateTime> AUDIT_TRAIL_DATE { get; set; }
        public Nullable<int> AUDIT_TRAIL_TYPE_ID { get; set; }
        public string AUDIT_TRAIL_DESCRIPTION { get; set; }
        public string AUDIT_TRAIL_DEVICE { get; set; }
    
        public virtual AUDIT_TRAIL_TYPE AUDIT_TRAIL_TYPE { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
