//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.CLIENT_MINE = new HashSet<CLIENT_MINE>();
        }
    
        public int CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_EMAIL_ADDRESS { get; set; }
        public string CLIENT_ADDRESS_BOX { get; set; }
        public string CLIENT_ADDRESS_STREET { get; set; }
        public string CLIENT_ADDRESS_TOWN { get; set; }
        public string CLIENT_ADDRESS_CODE { get; set; }
        public Nullable<int> CLIENT_CONTACT_NUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT_MINE> CLIENT_MINE { get; set; }
    }
}
