//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_MINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT_MINE()
        {
            this.CLIENT_ROUTE = new HashSet<CLIENT_ROUTE>();
        }
    
        public int CLIENT_MINE_ID { get; set; }
        public Nullable<int> MINE_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> DESTINATION_ID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual MINE MINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT_ROUTE> CLIENT_ROUTE { get; set; }
    }
}
