//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE_CONTRACT()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public string EMPLOYEE_CONTRACT_ID { get; set; }
        public Nullable<int> EMPLOYEE_CONTRACT_SALARY { get; set; }
        public Nullable<System.DateTime> EMPLOYEE_CONTRACT_START_DATE { get; set; }
        public Nullable<System.DateTime> EMPLOYEE_CONTRACT_END_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
    }
}
