//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINTENANCE_PRODUCT
    {
        public int MAINTENANCE_PRODUCT1 { get; set; }
        public Nullable<int> MAINTENANCE_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> MAINTENANCE_PRODUCT_QUANTITY { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual MAINTENANCE MAINTENANCE { get; set; }
    }
}
