//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINTENANCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAINTENANCE()
        {
            this.MAINTENANCE_PRODUCT = new HashSet<MAINTENANCE_PRODUCT>();
        }
    
        public int MAINTENANCE_ID { get; set; }
        public Nullable<int> VEHICLE_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<int> MAINTENANCE_STATUS_ID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAINTENANCE_PRODUCT> MAINTENANCE_PRODUCT { get; set; }
        public virtual MAINTENANCE_STATUS MAINTENANCE_STATUS { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
