//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MINE()
        {
            this.CLIENT_MINE = new HashSet<CLIENT_MINE>();
        }
    
        public int MINE_ID { get; set; }
        public string MINE_NAME { get; set; }
        public Nullable<int> PROVINCE_ID { get; set; }
    
        public virtual PROVINCE PROVINCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT_MINE> CLIENT_MINE { get; set; }
    }
}
