//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UTRANSPORTDATABASEEntities : DbContext
    {
        public UTRANSPORTDATABASEEntities()
            : base("name=UTRANSPORTDATABASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TITLE> TITLEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<TRAILER_STATUS> TRAILER_STATUS { get; set; }
        public virtual DbSet<TRUCK_PICKUP> TRUCK_PICKUP { get; set; }
        public virtual DbSet<VEHICLE_STATUS> VEHICLE_STATUS { get; set; }
        public virtual DbSet<DEALERSHIP> DEALERSHIPs { get; set; }
        public virtual DbSet<VEHICLE_DEALERSHIP_SERVICE> VEHICLE_DEALERSHIP_SERVICE { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<EMPLOYEE_CONTRACT> EMPLOYEE_CONTRACT { get; set; }
        public virtual DbSet<VEHICLE> VEHICLEs { get; set; }
        public virtual DbSet<TRAILER> TRAILERs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCT_TYPE> PRODUCT_TYPE { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERs { get; set; }
        public virtual DbSet<ORDERS_STATUS> ORDERS_STATUS { get; set; }
        public virtual DbSet<EMPLOYEE_TYPE> EMPLOYEE_TYPE { get; set; }
        public virtual DbSet<PROVINCE> PROVINCEs { get; set; }
        public virtual DbSet<CLIENT_ROUTE> CLIENT_ROUTE { get; set; }
        public virtual DbSet<MINE> MINE { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<CLIENT_MINE> CLIENT_MINE { get; set; }
        public virtual DbSet<DESTINATION> DESTINATIONs { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<ORDERS_LINE> ORDERS_LINE { get; set; }
        public virtual DbSet<AUDIT_TRAIL> AUDIT_TRAIL { get; set; }
        public virtual DbSet<AUDIT_TRAIL_TYPE> AUDIT_TRAIL_TYPE { get; set; }
        public virtual DbSet<MAINTENANCE_PRODUCT> MAINTENANCE_PRODUCT { get; set; }
        public virtual DbSet<MAINTENANCE_STATUS> MAINTENANCE_STATUS { get; set; }
        public virtual DbSet<MAINTENANCE> MAINTENANCEs { get; set; }
    }
}
