//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAILER()
        {
            this.VEHICLEs = new HashSet<VEHICLE>();
        }
    
        public int TRAILER_ID { get; set; }
        public string TRAILER_REGISTRATIONNUMBER { get; set; }
        public string TRAILER_BRAND { get; set; }
        public string TRAILER_NAME { get; set; }
        public string TRAILER_IMAGE_NAME { get; set; }
        public byte[] TRAILER_IMAGE { get; set; }
        public Nullable<int> TRAILER_STATUS_ID { get; set; }
        public Nullable<int> TRAILER_WEIGHT { get; set; }
    
        public virtual TRAILER_STATUS TRAILER_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE> VEHICLEs { get; set; }
    }
}
