//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUCK_PICKUP
    {
        public int TRUCK_PICKUP_ID { get; set; }
        public string TRUCK_PICKUP_STATUS { get; set; }
    }
}
