//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USERS_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string USERS_USERNAME { get; set; }
        public string USERS_PASSWORD { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
