//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICLE()
        {
            this.VEHICLE_DEALERSHIP_SERVICE = new HashSet<VEHICLE_DEALERSHIP_SERVICE>();
            this.MAINTENANCEs = new HashSet<MAINTENANCE>();
        }
    
        public int VEHICLE_ID { get; set; }
        public string VEHICLE_REGISTRATIONNUMBER { get; set; }
        public string VEHICLE_PLATENUMBER { get; set; }
        public string VEHICLE_BRAND { get; set; }
        public string VEHICLE_NAME { get; set; }
        public string VEHICLE_IMAGE_NAME { get; set; }
        public byte[] VEHICLE_IMAGE { get; set; }
        public Nullable<int> VEHICLE_STATUS_ID { get; set; }
        public Nullable<int> VEHICLE_WEIGHT { get; set; }
        public Nullable<int> TRAILER_ID { get; set; }
    
        public virtual VEHICLE_STATUS VEHICLE_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE_DEALERSHIP_SERVICE> VEHICLE_DEALERSHIP_SERVICE { get; set; }
        public virtual TRAILER TRAILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAINTENANCE> MAINTENANCEs { get; set; }
    }
}
