//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_DEALERSHIP_SERVICE
    {
        public int VEHICLE_SERVICE_ID { get; set; }
        public Nullable<System.DateTime> VEHICLE_SERVICE_DATE { get; set; }
        public Nullable<System.DateTime> VEHICLE_SERVICE_NEXT_DATE { get; set; }
        public Nullable<int> VEHICLE_ID { get; set; }
        public Nullable<int> DEALERSHIP_ID { get; set; }
    
        public virtual DEALERSHIP DEALERSHIP { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
