//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMPLOYEE_ID { get; set; }
        public Nullable<int> TITLE_ID { get; set; }
        public byte[] EMPLOYEE_IMAGE { get; set; }
        public string EMPLOYEE_NAMES { get; set; }
        public string EMPLOYEE_SURNAME { get; set; }
        public string EMPLOYEE_EMAIL_ADDRESS { get; set; }
        public string EMPLOYEE_CONTACT_NO { get; set; }
        public string IDENTITY_NO { get; set; }
        public Nullable<int> EMPLOYEE_CONTRACT_ID { get; set; }
        public Nullable<int> EMPLOYEE_TYPE_ID { get; set; }
    
        public virtual EMPLOYEE_CONTRACT EMPLOYEE_CONTRACT { get; set; }
        public virtual EMPLOYEE_TYPE EMPLOYEE_TYPE { get; set; }
        public virtual TITLE TITLE { get; set; }
    }
}
